Naranja_TeamHideshoalCave_G24_M76_MapScripts::
	.byte 0


Naranja_TeamHideshoalCave_G24_M76_EventScript_OBJ_EVENT_GFX_ITEM_BALL_LocalId5::
# 8 "data/maps/Naranja_TeamHideshoalCave_G24_M76/scripts.pory"
	setorcopyvar VAR_0x8000, 8
# 9 "data/maps/Naranja_TeamHideshoalCave_G24_M76/scripts.pory"
	setorcopyvar VAR_0x8001, 1
# 10 "data/maps/Naranja_TeamHideshoalCave_G24_M76/scripts.pory"
	callstd 1
	end

