Naranja_IslaMoro_G00_M22_MapScripts::
	.byte 0


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId1::
# 8 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_ISLA_MORO_154, Naranja_IslaMoro_G00_M22_Text_081B926B, Naranja_IslaMoro_G00_M22_Text_081B92B7
# 9 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_081B92E7, MSGBOX_AUTOCLOSE
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId3::
# 14 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_ISLA_MORO_444, Naranja_IslaMoro_G00_M22_Text_081B94C8, Naranja_IslaMoro_G00_M22_Text_081B94F2
# 15 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_081B94FF, MSGBOX_AUTOCLOSE
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId4::
# 20 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_ISLA_MORO_445, Naranja_IslaMoro_G00_M22_Text_081B9538, Naranja_IslaMoro_G00_M22_Text_081B956B
# 21 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_081B9589, MSGBOX_AUTOCLOSE
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId5::
# 26 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle_double TRAINER_NARANJA_ISLA_MORO_692, Naranja_IslaMoro_G00_M22_Text_081B95CB, Naranja_IslaMoro_G00_M22_Text_081B95FB, Naranja_IslaMoro_G00_M22_Text_081B9672
# 27 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_081B9630, MSGBOX_AUTOCLOSE
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_TUBER_M_SWIMMING_LocalId6::
# 32 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle_double TRAINER_NARANJA_ISLA_MORO_692, Naranja_IslaMoro_G00_M22_Text_081B96AB, Naranja_IslaMoro_G00_M22_Text_081B9707, Naranja_IslaMoro_G00_M22_Text_081B9788
# 33 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_081B9735, MSGBOX_AUTOCLOSE
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId2::
# 38 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	msgbox Naranja_IslaMoro_G00_M22_Text_08170C26, MSGBOX_NPC
	end


Naranja_IslaMoro_G00_M22_Text_08170C26::
# 42 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I left my POKéMON at the DAY CARE.\pWhen I got it back, it had a new move\nthat I didn’t teach it.\lI was really, really surprised.$"

Naranja_IslaMoro_G00_M22_Text_081B926B::
# 46 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Yawn...\pI must have drifted off to sleep while\nI was drifting in the waves.$"

Naranja_IslaMoro_G00_M22_Text_081B92B7::
# 50 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Ahaha, I lost...\nI’ll take a snooze, I think...$"

Naranja_IslaMoro_G00_M22_Text_081B92E7::
# 54 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Floating and being rocked by the\nwaves - it’s like sleeping in a plush,\lcomfy bed.$"

Naranja_IslaMoro_G00_M22_Text_081B94C8::
# 58 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Do you know a little town called\nDEWFORD?$"

Naranja_IslaMoro_G00_M22_Text_081B94F2::
# 62 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I hate this!$"

Naranja_IslaMoro_G00_M22_Text_081B94FF::
# 66 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "A weird saying is getting really\ntrendy at DEWFORD HALL.$"

Naranja_IslaMoro_G00_M22_Text_081B9538::
# 70 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Did you want to battle me?\nSure, I’ll go with you!$"

Naranja_IslaMoro_G00_M22_Text_081B956B::
# 74 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I wasn’t good enough for you.$"

Naranja_IslaMoro_G00_M22_Text_081B9589::
# 78 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I think you’re going to keep getting\nbetter. I’ll go for it, too!$"

Naranja_IslaMoro_G00_M22_Text_081B95CB::
# 82 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: We challenge you as a sister\nand brother!$"

Naranja_IslaMoro_G00_M22_Text_081B95FB::
# 86 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: Awesome.\nYou’re in a different class of tough.$"

Naranja_IslaMoro_G00_M22_Text_081B9630::
# 90 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: Do you have any friends who\nwould go to the beach with you?$"

Naranja_IslaMoro_G00_M22_Text_081B9672::
# 94 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: If you want to battle with us,\nbring more POKéMON.$"

Naranja_IslaMoro_G00_M22_Text_081B96AB::
# 98 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: We always battle POKéMON, me\nand my sister.\pI always lose, but we can beat you\n2-on-2!$"

Naranja_IslaMoro_G00_M22_Text_081B9707::
# 102 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: Wowee, you’re at a higher level\nthan us!$"

Naranja_IslaMoro_G00_M22_Text_081B9735::
# 106 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: My sister gave me my POKéMON.\nI raised it, and now it’s my important\lpartner!$"

Naranja_IslaMoro_G00_M22_Text_081B9788::
# 110 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: If you want to battle us, go\nbring some more POKéMON!$"
