Naranja_IslaMoro_G00_M22_MapScripts::
	.byte 0


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId1::
# 8 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_MORO_154, LOCALID_NONE, Naranja_IslaMoro_G00_M22_Text_081B926B, Naranja_IslaMoro_G00_M22_Text_081B92B7
# 9 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_081B92E7
# 10 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 6
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId3::
# 15 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_MORO_444, LOCALID_NONE, Naranja_IslaMoro_G00_M22_Text_081B94C8, Naranja_IslaMoro_G00_M22_Text_081B94F2
# 16 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_081B94FF
# 17 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 6
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId4::
# 22 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_MORO_445, LOCALID_NONE, Naranja_IslaMoro_G00_M22_Text_081B9538, Naranja_IslaMoro_G00_M22_Text_081B956B
# 23 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_081B9589
# 24 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 6
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId5::
# 29 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle TRAINER_BATTLE_DOUBLE, TRAINER_NARANJA_ISLA_MORO_692, LOCALID_NONE, Naranja_IslaMoro_G00_M22_Text_081B95CB, Naranja_IslaMoro_G00_M22_Text_081B95FB, Naranja_IslaMoro_G00_M22_Text_081B9672
# 30 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_081B9630
# 31 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 6
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_TUBER_M_SWIMMING_LocalId6::
# 36 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	trainerbattle TRAINER_BATTLE_DOUBLE, TRAINER_NARANJA_ISLA_MORO_692, LOCALID_NONE, Naranja_IslaMoro_G00_M22_Text_081B96AB, Naranja_IslaMoro_G00_M22_Text_081B9707, Naranja_IslaMoro_G00_M22_Text_081B9788
# 37 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_081B9735
# 38 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 6
	end


Naranja_IslaMoro_G00_M22_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId2::
# 43 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	loadword 0, Naranja_IslaMoro_G00_M22_Text_08170C26
# 44 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	callstd 2
	end


Naranja_IslaMoro_G00_M22_Text_08170C26::
# 48 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I left my POKéMON at the DAY CARE.\pWhen I got it back, it had a new move\nthat I didn’t teach it.\lI was really, really surprised.$"

Naranja_IslaMoro_G00_M22_Text_081B926B::
# 52 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Yawn...\pI must have drifted off to sleep while\nI was drifting in the waves.$"

Naranja_IslaMoro_G00_M22_Text_081B92B7::
# 56 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Ahaha, I lost...\nI’ll take a snooze, I think...$"

Naranja_IslaMoro_G00_M22_Text_081B92E7::
# 60 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Floating and being rocked by the\nwaves - it’s like sleeping in a plush,\lcomfy bed.$"

Naranja_IslaMoro_G00_M22_Text_081B94C8::
# 64 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Do you know a little town called\nDEWFORD?$"

Naranja_IslaMoro_G00_M22_Text_081B94F2::
# 68 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I hate this!$"

Naranja_IslaMoro_G00_M22_Text_081B94FF::
# 72 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "A weird saying is getting really\ntrendy at DEWFORD HALL.$"

Naranja_IslaMoro_G00_M22_Text_081B9538::
# 76 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "Did you want to battle me?\nSure, I’ll go with you!$"

Naranja_IslaMoro_G00_M22_Text_081B956B::
# 80 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I wasn’t good enough for you.$"

Naranja_IslaMoro_G00_M22_Text_081B9589::
# 84 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "I think you’re going to keep getting\nbetter. I’ll go for it, too!$"

Naranja_IslaMoro_G00_M22_Text_081B95CB::
# 88 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: We challenge you as a sister\nand brother!$"

Naranja_IslaMoro_G00_M22_Text_081B95FB::
# 92 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: Awesome.\nYou’re in a different class of tough.$"

Naranja_IslaMoro_G00_M22_Text_081B9630::
# 96 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: Do you have any friends who\nwould go to the beach with you?$"

Naranja_IslaMoro_G00_M22_Text_081B9672::
# 100 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "LISA: If you want to battle with us,\nbring more POKéMON.$"

Naranja_IslaMoro_G00_M22_Text_081B96AB::
# 104 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: We always battle POKéMON, me\nand my sister.\pI always lose, but we can beat you\n2-on-2!$"

Naranja_IslaMoro_G00_M22_Text_081B9707::
# 108 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: Wowee, you’re at a higher level\nthan us!$"

Naranja_IslaMoro_G00_M22_Text_081B9735::
# 112 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: My sister gave me my POKéMON.\nI raised it, and now it’s my important\lpartner!$"

Naranja_IslaMoro_G00_M22_Text_081B9788::
# 116 "data/maps/Naranja_IslaMoro_G00_M22/scripts.pory"
	.string "RAY: If you want to battle us, go\nbring some more POKéMON!$"
