Naranja_AbandonedShip_Corridors_1F_MapScripts::
	.byte 0


Naranja_AbandonedShip_Corridors_1F_EventScript_Youngster::
# 8 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	msgbox Naranja_AbandonedShip_Corridors_1F_Text_081984D8, MSGBOX_NPC
	end


Naranja_AbandonedShip_Corridors_1F_EventScript_TuberM::
# 13 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_BANDONED_SHIP_066, Naranja_AbandonedShip_Corridors_1F_Text_0819843D, Naranja_AbandonedShip_Corridors_1F_Text_08198479
# 14 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	msgbox Naranja_AbandonedShip_Corridors_1F_Text_08198493, MSGBOX_AUTOCLOSE
	end


Naranja_AbandonedShip_Corridors_1F_Text_0819843D::
# 18 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	.string "What’s so funny about having my inner\ntube aboard the ship?$"

Naranja_AbandonedShip_Corridors_1F_Text_08198479::
# 22 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	.string "Whoa, you overwhelmed me!$"

Naranja_AbandonedShip_Corridors_1F_Text_08198493::
# 26 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	.string "It’s not easy throwing POKé BALLS\nwhile hanging on to an inner tube!$"

Naranja_AbandonedShip_Corridors_1F_Text_081984D8::
# 30 "data/maps/Naranja_AbandonedShip_Corridors_1F/scripts.pory"
	.string "Isn’t it fun here?\nI get excited just being here!$"
