Naranja_IslaNueva_G15_M09_MapScripts::
	.byte 0


Naranja_IslaNueva_G15_M09_EventScript_OBJ_EVENT_GFX_MANIAC_LocalId1::
# 8 "data/maps/Naranja_IslaNueva_G15_M09/scripts.pory"
	msgbox Naranja_IslaNueva_G15_M09_Text_0818FDEC, MSGBOX_NPC
	end


Naranja_IslaNueva_G15_M09_EventScript_OBJ_EVENT_GFX_GIRL_3_LocalId2::
# 13 "data/maps/Naranja_IslaNueva_G15_M09/scripts.pory"
	msgbox Naranja_IslaNueva_G15_M09_Text_0818FE7B, MSGBOX_NPC
	end


Naranja_IslaNueva_G15_M09_Text_0818FDEC::
# 17 "data/maps/Naranja_IslaNueva_G15_M09/scripts.pory"
	.string "There appears to be some connection\nbetween SOOTOPOLIS and MT. PYRE.\pMy friends and I did some research on\nit at the lab where I used to work.$"

Naranja_IslaNueva_G15_M09_Text_0818FE7B::
# 21 "data/maps/Naranja_IslaNueva_G15_M09/scripts.pory"
	.string "My big brother used to study the sea.$"
