Naranja_ValenciaIsland_House4_MapScripts::
	.byte 0


Naranja_ValenciaIsland_House4_EventScript_Man5::
# 8 "data/maps/Naranja_ValenciaIsland_House4/scripts.pory"
	msgbox Naranja_ValenciaIsland_House4_Text_0818BEE8, MSGBOX_NPC
	end


Naranja_ValenciaIsland_House4_EventScript_Man1::
# 13 "data/maps/Naranja_ValenciaIsland_House4/scripts.pory"
	msgbox Naranja_ValenciaIsland_House4_Text_0818BF4E, MSGBOX_NPC
	end


Naranja_ValenciaIsland_House4_Text_0818BEE8::
# 17 "data/maps/Naranja_ValenciaIsland_House4/scripts.pory"
	.string "’’Si mi voz muriera en tierra\nllevadla al nivel del mar\ly dejadla en la ribera.’’\pLo decía Alberti…$"

Naranja_ValenciaIsland_House4_Text_0818BF4E::
# 21 "data/maps/Naranja_ValenciaIsland_House4/scripts.pory"
	.string "Antes vivía en la isla MANDARIN,\nera una ciudad enorme y ruidosa\lcomparado con la tranquilidad de aquí$"
