Naranja_TangeloIsland_FriendshipRatersHouse_MapScripts::
	.byte 0


Naranja_TangeloIsland_FriendshipRatersHouse_EventScript_Lass::
# 8 "data/maps/Naranja_TangeloIsland_FriendshipRatersHouse/scripts.pory"
	msgbox Naranja_TangeloIsland_FriendshipRatersHouse_Text_081BC0C3, MSGBOX_DEFAULT
# 9 "data/maps/Naranja_TangeloIsland_FriendshipRatersHouse/scripts.pory"
	release
	end


Naranja_TangeloIsland_FriendshipRatersHouse_Text_081BC0C3::
# 13 "data/maps/Naranja_TangeloIsland_FriendshipRatersHouse/scripts.pory"
	.string "¡Hey tìo! ¿Acaso es que ve tu culo\nque yo te moleste a tì?\p¡Déjame ver la tele, hermano!$"
