Naranja_IslaMandarina_G06_M07_MapScripts::
	.byte 0


Naranja_IslaMandarina_G06_M07_EventScript_OBJ_EVENT_GFX_LITTLE_BOY_1_LocalId2::
# 8 "data/maps/Naranja_IslaMandarina_G06_M07/scripts.pory"
	msgbox Naranja_IslaMandarina_G06_M07_Text_0817831D, MSGBOX_NPC
	end


Naranja_IslaMandarina_G06_M07_EventScript_OBJ_EVENT_GFX_BEAUTY_LocalId1::
# 13 "data/maps/Naranja_IslaMandarina_G06_M07/scripts.pory"
	msgbox Naranja_IslaMandarina_G06_M07_Text_08178D11, MSGBOX_NPC
	end


Naranja_IslaMandarina_G06_M07_Text_0817831D::
# 17 "data/maps/Naranja_IslaMandarina_G06_M07/scripts.pory"
	.string "¡Fiu fiu fiuuu!\pAcabaremos con el MAL mundial\p¡Destrucción!\p¡Hoy empieza una NUEVA ERA!\p¡Y es SOLO nuestra!$"

Naranja_IslaMandarina_G06_M07_Text_08178D11::
# 21 "data/maps/Naranja_IslaMandarina_G06_M07/scripts.pory"
	.string "Me siento una mujer modélica.\pSiempre tengo tiempo para preparar las\nzapatillas y una gran cena a mi marido\len cuanto llega.$"
