Naranja_IslaMellsweet_G14_M10_MapScripts::
	.byte 0


Naranja_IslaMellsweet_G14_M10_EventScript_OBJ_EVENT_GFX_SCIENTIST_1_LocalId3::
# 8 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	loadword 0, Naranja_IslaMellsweet_G14_M10_Text_0818E483
# 9 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	callstd 2
	end


Naranja_IslaMellsweet_G14_M10_EventScript_OBJ_EVENT_GFX_GENTLEMAN_LocalId2::
# 14 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	loadword 0, Naranja_IslaMellsweet_G14_M10_Text_0818E4EE
# 15 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	callstd 2
	end


Naranja_IslaMellsweet_G14_M10_EventScript_OBJ_EVENT_GFX_BOY_4_LocalId1::
# 20 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	loadword 0, Naranja_IslaMellsweet_G14_M10_Text_0818E564
# 21 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	callstd 2
	end


Naranja_IslaMellsweet_G14_M10_Text_0818E483::
# 25 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	.string "MOSSDEEP has mainly sunny weather,\nand its winds are stable.\pIt’s an ideal location for launching\nrockets.$"

Naranja_IslaMellsweet_G14_M10_Text_0818E4EE::
# 29 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	.string "If only I was a little younger, I would\nhave liked being an astronaut...\pNo... It’s not too late!\nI can and will try!$"

Naranja_IslaMellsweet_G14_M10_Text_0818E564::
# 33 "data/maps/Naranja_IslaMellsweet_G14_M10/scripts.pory"
	.string "I wish ordinary people could go into\nspace one day...$"
