Naranja_KumquatIsland_ContestHall_MapScripts::
	.byte 0


Naranja_KumquatIsland_ContestHall_EventScript_Boy1::
# 8 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081890D4, MSGBOX_NPC
	end


Naranja_KumquatIsland_ContestHall_EventScript_Boy3::
# 13 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_0818915F, MSGBOX_NPC
	end


Naranja_KumquatIsland_ContestHall_EventScript_Girl3::
# 18 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189221, MSGBOX_NPC
	end


Naranja_KumquatIsland_ContestHall_EventScript_Sailor::
# 23 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189299, MSGBOX_NPC
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman4::
# 28 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189301, MSGBOX_NPC
# 29 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 30 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_4, Naranja_RusturfTunnel_Movement_081A083D
# 31 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 32 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_ContestJudge::
# 37 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189366, MSGBOX_NPC
# 38 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 39 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_CONTEST_JUDGE, Naranja_RusturfTunnel_Movement_081A083D
# 40 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 41 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_BlackBelt::
# 46 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081893CE, MSGBOX_NPC
# 47 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 48 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_BLACK_BELT, Naranja_RusturfTunnel_Movement_081A083D
# 49 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 50 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_OldMan1::
# 55 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189463, MSGBOX_NPC
# 56 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 57 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_OLD_MAN_1, Naranja_RusturfTunnel_Movement_081A083D
# 58 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 59 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Maniac::
# 64 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189512, MSGBOX_NPC
# 65 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 66 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_MANIAC, Naranja_RusturfTunnel_Movement_081A083D
# 67 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 68 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman6::
# 73 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_0818956B, MSGBOX_NPC
# 74 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 75 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_6, Naranja_RusturfTunnel_Movement_081A083D
# 76 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 77 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_OldWoman1::
# 82 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081895F3, MSGBOX_SIGN
	end


Naranja_KumquatIsland_ContestHall_EventScript_Boy1_2::
# 87 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189617, MSGBOX_NPC
# 88 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 89 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_BOY_1_12, Naranja_RusturfTunnel_Movement_081A083D
# 90 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 91 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Camper::
# 96 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081896BE, MSGBOX_NPC
# 97 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 98 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_CAMPER, Naranja_RusturfTunnel_Movement_081A083D
# 99 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 100 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman7::
# 105 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081896FE, MSGBOX_NPC
# 106 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 107 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_7, Naranja_RusturfTunnel_Movement_081A083D
# 108 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 109 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman4_2::
# 114 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189771, MSGBOX_NPC
# 115 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 116 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_4_2, Naranja_RusturfTunnel_Movement_081A083D
# 117 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 118 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_ContestJudge_2::
# 123 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_081897AA, MSGBOX_NPC
# 124 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 125 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_CONTEST_JUDGE_2, Naranja_RusturfTunnel_Movement_081A083D
# 126 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 127 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman5::
# 132 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_0818980B, MSGBOX_NPC
# 133 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 134 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_5, Naranja_RusturfTunnel_Movement_081A083D
# 135 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 136 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_LittleGirl1::
# 141 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189874, MSGBOX_NPC
# 142 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 143 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_LITTLE_GIRL_1, Naranja_RusturfTunnel_Movement_081A083D
# 144 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 145 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_PsychicM::
# 150 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_0818990A, MSGBOX_NPC
# 151 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 152 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_PSYCHIC_M, Naranja_RusturfTunnel_Movement_081A083D
# 153 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 154 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman2::
# 159 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189981, MSGBOX_NPC
# 160 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 161 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_2, Naranja_RusturfTunnel_Movement_081A083D
# 162 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 163 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman3::
# 168 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189A1D, MSGBOX_NPC
# 169 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 170 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_3, Naranja_RusturfTunnel_Movement_081A083D
# 171 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 172 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Man1::
# 177 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189A82, MSGBOX_NPC
# 178 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 179 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_MAN_1_21, Naranja_RusturfTunnel_Movement_081A083D
# 180 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 181 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman1::
# 186 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189AE1, MSGBOX_NPC
# 187 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 188 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_1_20, Naranja_RusturfTunnel_Movement_081A083D
# 189 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 190 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman4_3::
# 195 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189B4E, MSGBOX_NPC
# 196 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 197 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_4_3, Naranja_RusturfTunnel_Movement_081A083D
# 198 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 199 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_ContestJudge_3::
# 204 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189BBF, MSGBOX_NPC
# 205 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 206 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_CONTEST_JUDGE_3, Naranja_RusturfTunnel_Movement_081A083D
# 207 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 208 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Boy2::
# 213 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189C29, MSGBOX_NPC
# 214 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 215 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_BOY_2, Naranja_RusturfTunnel_Movement_081A083D
# 216 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 217 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Girl2::
# 222 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189C67, MSGBOX_NPC
# 223 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 224 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_GIRL_2, Naranja_RusturfTunnel_Movement_081A083D
# 225 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 226 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Boy3_2::
# 231 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189CB3, MSGBOX_NPC
# 232 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 233 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_BOY_3_2, Naranja_RusturfTunnel_Movement_081A083D
# 234 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 235 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_OldWoman1_2::
# 240 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189D11, MSGBOX_NPC
# 241 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 242 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_OLD_WOMAN_1_2, Naranja_RusturfTunnel_Movement_081A083D
# 243 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 244 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Woman3_2::
# 249 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 250 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_3_2, Naranja_KumquatIsland_Movement_081A0839
# 251 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 252 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	delay 0x19
# 253 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_WOMAN_3_2, Naranja_RusturfTunnel_Movement_081A083D
# 254 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 255 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189DA2, MSGBOX_SIGN
# 256 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_LittleGirl2::
# 261 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189E5F, MSGBOX_NPC
# 262 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 263 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_LITTLE_GIRL_2, Naranja_RusturfTunnel_Movement_081A083D
# 264 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 265 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Man1_2::
# 270 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189DF3, MSGBOX_NPC
# 271 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	lockall
# 272 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	applymovement LOCALID_NARANJA_KUMQUAT_ISLAND_CONTEST_HALL_MAN_1_30, Naranja_RusturfTunnel_Movement_081A083D
# 273 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	waitmovement LOCALID_NONE
# 274 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	releaseall
	end


Naranja_KumquatIsland_ContestHall_EventScript_Sign_1::
# 279 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189EF3, MSGBOX_SIGN
	end


Naranja_KumquatIsland_ContestHall_EventScript_Sign_2::
# 284 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189F29, MSGBOX_SIGN
	end


Naranja_KumquatIsland_ContestHall_EventScript_Sign_3::
# 289 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	msgbox Naranja_KumquatIsland_ContestHall_Text_08189F5C, MSGBOX_SIGN
	end


Naranja_KumquatIsland_ContestHall_Text_081890D4::
# 293 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "This POKéMON won the BEAUTY CONTEST\nhere before.\pWell, guess what? Today, I made it\nwin a SMARTNESS CONTEST!\pMy abilities scare even me...$"

Naranja_KumquatIsland_ContestHall_Text_0818915F::
# 297 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "I’ve entered a bunch of CONTESTS,\nso I’m seeing how things work.\pIf you’re in a COOLNESS CONTEST,\ncool moves go over as appeals.\pBut smart moves and cute moves\ndon’t go over well, for instance.$"

Naranja_KumquatIsland_ContestHall_Text_08189221::
# 301 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "That young man who won earlier had\na whole bunch of different オカキクケS.\pCan you win if you had that many\nof those things?$"

Naranja_KumquatIsland_ContestHall_Text_08189299::
# 305 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Whoa, isn’t this place humongous!\pThe tension in the air... It’s not\nlike a CONTEST hall in the sticks.$"

Naranja_KumquatIsland_ContestHall_Text_08189301::
# 309 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "MC: Okay, SMART POKéMON and their\nTRAINERS, are you ready?!\pGive it your best showing!\nLet’s appeal!$"

Naranja_KumquatIsland_ContestHall_Text_08189366::
# 313 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "JUDGE: Are you enjoying this CONTEST?\pCome back with three friends, and\nall of you may enter a CONTEST!$"

Naranja_KumquatIsland_ContestHall_Text_081893CE::
# 317 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Ayayayay...\nI entered the wrong CONTEST.\pI entered this tough POKéMON in the\nSMARTNESS CONTEST...\pCome on, wow them with a smart-looking\nROCK SMASH.$"

Naranja_KumquatIsland_ContestHall_Text_08189463::
# 321 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "I’ve spent many a year, and all my\nwisdom besides, raising this POKéMON\lto be smart.\pIt won’t be easily bested by some\nyoung pup’s POKéMON.\pMy dear wife, are you seeing this?$"

Naranja_KumquatIsland_ContestHall_Text_08189512::
# 325 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "There it is!\pIf my POKéMON pulls a smart move next,\nthe audience’s excitement will peak!$"

Naranja_KumquatIsland_ContestHall_Text_0818956B::
# 329 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Oh, dear, no!\pMy darling ZUBAT’s LEECH LIFE is so\ncute I kept using it over and over!\pBut these mean people don’t appreciate\nit at all!$"

Naranja_KumquatIsland_ContestHall_Text_081895F3::
# 333 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Kiyaaah! You’re beautiful, Grandpa!$"

Naranja_KumquatIsland_ContestHall_Text_08189617::
# 337 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Even when TRAINERS enter the same\nkind of POKéMON, they all seem to use\ldifferent moves for appeals.\pIt’s just like the way people have\ndifferent styles for battling.$"

Naranja_KumquatIsland_ContestHall_Text_081896BE::
# 341 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "I think the POKéMON look smarter\nthan their TRAINERS. By a lot.$"

Naranja_KumquatIsland_ContestHall_Text_081896FE::
# 345 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "When all’s said and done, I still love\nSMARTNESS CONTESTS.\pThat intellectual green color...\nIt’s so... So... Cool.$"

Naranja_KumquatIsland_ContestHall_Text_08189771::
# 349 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "MC: Are you entering the BEAUTY\nCONTEST, too? Good luck!$"

Naranja_KumquatIsland_ContestHall_Text_081897AA::
# 353 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "JUDGE: Ah, every POKéMON here is a\nmodel of pristine beauty!\pWhy, I almost forgot to score them!$"

Naranja_KumquatIsland_ContestHall_Text_0818980B::
# 357 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "A POKéMON this beautiful...\nThere isn’t another one like it.\pEveryone’s eyes will be glued to\nmy beauty.$"

Naranja_KumquatIsland_ContestHall_Text_08189874::
# 361 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Waaaah!\pI brushed and groomed my POKéMON\ncarefully for this CONTEST...\pBut I overdid it...\nMy POKéMON’s coat turned all scraggly...\pWhat should I do?$"

Naranja_KumquatIsland_ContestHall_Text_0818990A::
# 365 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "This AURORA BEAM is so dazzling,\nthe JUDGE won’t be able to see it.\pUh, wait a second...\nThat’ll be meaningless, then!$"

Naranja_KumquatIsland_ContestHall_Text_08189981::
# 369 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "This pretty POKéMON looks just like\nme when I was younger.\pRight when I said that, my husband\nspewed the coffee he was drinking.\pDid I say something funny?$"

Naranja_KumquatIsland_ContestHall_Text_08189A1D::
# 373 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "You know, as a woman, if I win at a\nBEAUTY CONTEST, sure it makes me\lhappy. More than usual, anyway.$"

Naranja_KumquatIsland_ContestHall_Text_08189A82::
# 377 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Wahahahah!\pWill you take a gander at all those\npretty POKéMON!\lI just love this sort of glitz!$"

Naranja_KumquatIsland_ContestHall_Text_08189AE1::
# 381 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "You can’t always win on just beauty\nalone.\pYou have to groom your POKéMON so\nit’s nice and glossy like mine.$"

Naranja_KumquatIsland_ContestHall_Text_08189B4E::
# 385 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "MC: Uh-oh! Hello!\nWe’re in the middle of a CONTEST!\pPlease enter at our registration\ncounter and come out, okay?$"

Naranja_KumquatIsland_ContestHall_Text_08189BBF::
# 389 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "JUDGE: Oh, such charming and cute\nappeals!\pOh, my goodness! What a perfectly\nadorable WATER SPORT appeal!$"

Naranja_KumquatIsland_ContestHall_Text_08189C29::
# 393 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Oh, no... My sweet AZURILL was\ndistracted by another POKéMON.$"

Naranja_KumquatIsland_ContestHall_Text_08189C67::
# 397 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "My POKéMON has never won in a battle,\nbut put it in a CONTEST and look out!$"

Naranja_KumquatIsland_ContestHall_Text_08189CB3::
# 401 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "My POKéMON’s PETAL DANCE is a marvel\nof elegance.\pI won’t let anyone disturb its\nperformance.$"

Naranja_KumquatIsland_ContestHall_Text_08189D11::
# 405 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Everyone’s POKéMON are very cute.\pHowever, if my POKéMON were to make\na cute appeal...\pI’m sure that it would be so much \ncuter than the others.$"

Naranja_KumquatIsland_ContestHall_Text_08189DA2::
# 409 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "My child is in this CONTEST.\pCome on, dear. Go for it!\nYour POKéMON is the best!$"

Naranja_KumquatIsland_ContestHall_Text_08189DF3::
# 413 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "I think that girl over there is the\ncutest of the lot.\pWhat’s that? They’re judging\nPOKéMON by their looks?$"

Naranja_KumquatIsland_ContestHall_Text_08189E5F::
# 417 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "Ohh, seeing all these cute POKéMON,\nthey make we want to get my own!\pI’m going to go catch some!$"

Naranja_KumquatIsland_ContestHall_Text_08189EF3::
# 421 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "BEAUTY CONTEST STAGE\nBE ALLURED BY BEAUTIFUL POKéMON!$"

Naranja_KumquatIsland_ContestHall_Text_08189F29::
# 425 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "CUTENESS CONTEST STAGE\nBE CHARMED BY CUTE POKéMON!$"

Naranja_KumquatIsland_ContestHall_Text_08189F5C::
# 429 "data/maps/Naranja_KumquatIsland_ContestHall/scripts.pory"
	.string "SMARTNESS CONTEST STAGE\nBE IMPRESSED BY SMART POKéMON!$"
