Naranja_IslaNueva_G15_M11_MapScripts::
	.byte 0


Naranja_IslaNueva_G15_M11_EventScript_OBJ_EVENT_GFX_OLD_MAN_2_LocalId1::
# 8 "data/maps/Naranja_IslaNueva_G15_M11/scripts.pory"
	msgbox Naranja_IslaNueva_G15_M11_Text_0818FFA9, MSGBOX_NPC
	end


Naranja_IslaNueva_G15_M11_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId2::
# 13 "data/maps/Naranja_IslaNueva_G15_M11/scripts.pory"
	msgbox Naranja_IslaNueva_G15_M11_Text_0819005B, MSGBOX_NPC
	end


Naranja_IslaNueva_G15_M11_Text_0818FFA9::
# 17 "data/maps/Naranja_IslaNueva_G15_M11/scripts.pory"
	.string "An underwater volcano erupted and\nforced itself up from the depths.\pIts crater emerged from the sea and\nbecame filled with rainwater.\pThat’s how SOOTOPOLIS CITY came into\nbeing.$"

Naranja_IslaNueva_G15_M11_Text_0819005B::
# 21 "data/maps/Naranja_IslaNueva_G15_M11/scripts.pory"
	.string "The cave that links SOOTOPOLIS and\nthe outside world...\pIt seems as if the cave was made to\nkeep something from getting out.\pOr am I just imagining things?$"
