Naranja_Route129_G00_M44_MapScripts::
	.byte 0


Naranja_Route129_G00_M44_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId1::
# 8 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ROUTE129_378, LOCALID_NONE, Naranja_Route129_G00_M44_Text_081C2161, Naranja_Route129_G00_M44_Text_081C2198
# 9 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	loadword 0, Naranja_Route129_G00_M44_Text_081C21B4
# 10 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	callstd 6
	end


Naranja_Route129_G00_M44_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId2::
# 15 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ROUTE129_387, LOCALID_NONE, Naranja_Route129_G00_M44_Text_081C21ED, Naranja_Route129_G00_M44_Text_081C222F
# 16 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	loadword 0, Naranja_Route129_G00_M44_Text_081C2243
# 17 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	callstd 6
	end


Naranja_Route129_G00_M44_EventScript_OBJ_EVENT_GFX_SWIMMER_M_LocalId4::
# 22 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ROUTE129_675, LOCALID_NONE, Naranja_Route129_G00_M44_Text_081C22C8, Naranja_Route129_G00_M44_Text_081C22EC
# 23 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	loadword 0, Naranja_Route129_G00_M44_Text_081C230F
# 24 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	callstd 6
	end


Naranja_Route129_G00_M44_EventScript_OBJ_EVENT_GFX_SWIMMER_F_LocalId3::
# 29 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ROUTE129_676, LOCALID_NONE, Naranja_Route129_G00_M44_Text_081C2349, Naranja_Route129_G00_M44_Text_081C2378
# 30 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	loadword 0, Naranja_Route129_G00_M44_Text_081C23A3
# 31 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	callstd 6
	end


Naranja_Route129_G00_M44_Text_081C2161::
# 35 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "This is my first triathlon.\nI’m all tense and nervous!$"

Naranja_Route129_G00_M44_Text_081C2198::
# 39 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Wroooaaar!\nI failed to win!$"

Naranja_Route129_G00_M44_Text_081C21B4::
# 43 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "If I’m all tensed up, I won’t be able to\ngive it my all.$"

Naranja_Route129_G00_M44_Text_081C21ED::
# 47 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "I’m in the middle of a triathlon, but,\nsure, why don’t we battle?$"

Naranja_Route129_G00_M44_Text_081C222F::
# 51 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "I was sure I’d win!$"

Naranja_Route129_G00_M44_Text_081C2243::
# 55 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Do you know what’s the greatest thing\nabout triathlons?\pTesting the limits of your own\nstrength and endurance against\lMother Nature!$"

Naranja_Route129_G00_M44_Text_081C22C8::
# 59 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Say hey, hey!\nLet’s get on with it!$"

Naranja_Route129_G00_M44_Text_081C22EC::
# 63 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Beat, I’m beaten.\nThat’s it, done!$"

Naranja_Route129_G00_M44_Text_081C230F::
# 67 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "There’s nothing for a loser.\nTime for me to beat it home.$"

Naranja_Route129_G00_M44_Text_081C2349::
# 71 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "What’s the hurry?\nLet’s take it slow and easy.$"

Naranja_Route129_G00_M44_Text_081C2378::
# 75 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Oh, my.\nI wanted to relax a little more...$"

Naranja_Route129_G00_M44_Text_081C23A3::
# 79 "data/maps/Naranja_Route129_G00_M44/scripts.pory"
	.string "Don’t you hate making mistakes when\nyou’re in a rush?\pThat’s why I try to take things\nslowly.$"
