Naranja_SinNombre_G25_M42_MapScripts::
	.byte 0


Naranja_SinNombre_G25_M42_EventScript_OBJ_EVENT_GFX_SAILOR_LocalId1::
# 8 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_SIN_NOMBRE_494, LOCALID_NONE, Naranja_SinNombre_G25_M42_Text_081993C1, Naranja_SinNombre_G25_M42_Text_0819941A
# 9 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	loadword 0, Naranja_SinNombre_G25_M42_Text_0819942E
# 10 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	callstd 6
	end


Naranja_SinNombre_G25_M42_EventScript_OBJ_EVENT_GFX_SAILOR_LocalId2::
# 15 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_SIN_NOMBRE_495, LOCALID_NONE, Naranja_SinNombre_G25_M42_Text_08199491, Naranja_SinNombre_G25_M42_Text_081994F7
# 16 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	loadword 0, Naranja_SinNombre_G25_M42_Text_08199508
# 17 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	callstd 6
	end


Naranja_SinNombre_G25_M42_Text_081993C1::
# 21 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "Arrrgh! I’m fed up and dog-tired of\ncleaning this huge place!\pLet’s have a quick battle!$"

Naranja_SinNombre_G25_M42_Text_0819941A::
# 25 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "Little bro, I lost!$"

Naranja_SinNombre_G25_M42_Text_0819942E::
# 29 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "We’re the CLEANUP BROTHERS!\pThe old one dumps the detergent,\nand the young one does the scrubbing!$"

Naranja_SinNombre_G25_M42_Text_08199491::
# 33 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "This is the bottom of the ship’s hull.\nThere’s plenty of room.\lIt’ll be alright for a POKéMON battle.$"

Naranja_SinNombre_G25_M42_Text_081994F7::
# 37 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "Big bro, I lost!$"

Naranja_SinNombre_G25_M42_Text_08199508::
# 41 "data/maps/Naranja_SinNombre_G25_M42/scripts.pory"
	.string "We’re the CLEANUP BROTHERS!\pThe old one dumps the detergent,\nand the young one does the scrubbing!$"
