Naranja_VictoryRoad_G24_M44_MapScripts::
	.byte 0


Naranja_VictoryRoad_G24_M44_EventScript_OBJ_EVENT_GFX_MAN_4_LocalId14::
# 8 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_VICTORY_ROAD_081, LOCALID_NONE, Naranja_VictoryRoad_G24_M44_Text_08197CE9, Naranja_VictoryRoad_G24_M44_Text_08197D42
# 9 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	loadword 0, Naranja_VictoryRoad_G24_M44_Text_08197D5B
# 10 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	callstd 6
	end


Naranja_VictoryRoad_G24_M44_EventScript_OBJ_EVENT_GFX_WOMAN_7_LocalId15::
# 15 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_VICTORY_ROAD_097, LOCALID_NONE, Naranja_VictoryRoad_G24_M44_Text_08197D98, Naranja_VictoryRoad_G24_M44_Text_08197DE8
# 16 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	loadword 0, Naranja_VictoryRoad_G24_M44_Text_08197E13
# 17 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	callstd 6
	end


Naranja_VictoryRoad_G24_M44_EventScript_OBJ_EVENT_GFX_WOMAN_7_LocalId16::
# 22 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_VICTORY_ROAD_098, LOCALID_NONE, Naranja_VictoryRoad_G24_M44_Text_08197E5D, Naranja_VictoryRoad_G24_M44_Text_08197EA6
# 23 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	loadword 0, Naranja_VictoryRoad_G24_M44_Text_08197EB6
# 24 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	callstd 6
	end


Naranja_VictoryRoad_G24_M44_EventScript_OBJ_EVENT_GFX_ITEM_BALL_LocalId18::
# 29 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	setorcopyvar VAR_0x8000, 0x13D
# 30 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	setorcopyvar VAR_0x8001, 1
# 31 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	callstd 1
	end


Naranja_VictoryRoad_G24_M44_EventScript_OBJ_EVENT_GFX_ITEM_BALL_LocalId19::
# 36 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	setorcopyvar VAR_0x8000, 0x13
# 37 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	setorcopyvar VAR_0x8001, 1
# 38 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	callstd 1
	end


Naranja_VictoryRoad_G24_M44_Text_08197CE9::
# 42 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "The thought that I’m getting closer to\nthe POKéMON LEAGUE...\pI’m getting stage fright...$"

Naranja_VictoryRoad_G24_M44_Text_08197D42::
# 46 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "I couldn’t do a thing...$"

Naranja_VictoryRoad_G24_M44_Text_08197D5B::
# 50 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "The POKéMON LEAGUE became distant\nagain... What a letdown...$"

Naranja_VictoryRoad_G24_M44_Text_08197D98::
# 54 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "To win your way through the POKéMON\nLEAGUE, you need the trust of your\lPOKéMON.$"

Naranja_VictoryRoad_G24_M44_Text_08197DE8::
# 58 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "Your relationship is based on\nsolid trust.$"

Naranja_VictoryRoad_G24_M44_Text_08197E13::
# 62 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "By being together all the time, trust\ngrows between POKéMON and TRAINERS.$"

Naranja_VictoryRoad_G24_M44_Text_08197E5D::
# 66 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "This isn’t the goal. It’s only a place\non the way to the POKéMON LEAGUE.$"

Naranja_VictoryRoad_G24_M44_Text_08197EA6::
# 70 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "That’s the way!$"

Naranja_VictoryRoad_G24_M44_Text_08197EB6::
# 74 "data/maps/Naranja_VictoryRoad_G24_M44/scripts.pory"
	.string "You’ll do fine, for sure!\nYour POKéMON are all eager to go!$"
