Naranja_IslaTrovita_G11_M08_MapScripts::
	.byte 0


Naranja_IslaTrovita_G11_M08_EventScript_OBJ_EVENT_GFX_MAN_4_LocalId1::
# 8 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	loadword 0, Naranja_IslaTrovita_G11_M08_Text_08184DB4
# 9 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	callstd 2
	end


Naranja_IslaTrovita_G11_M08_EventScript_OBJ_EVENT_GFX_WOMAN_7_LocalId2::
# 14 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	loadword 0, Naranja_IslaTrovita_G11_M08_Text_08184DE9
# 15 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	callstd 2
	end


Naranja_IslaTrovita_G11_M08_Text_08184DB4::
# 19 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	.string "Every POKéMON has a special ability\nthat it can use.$"

Naranja_IslaTrovita_G11_M08_Text_08184DE9::
# 23 "data/maps/Naranja_IslaTrovita_G11_M08/scripts.pory"
	.string "POKéMON are such strange creatures.$"
