Naranja_IslaTangelo_G02_M01_MapScripts::
	.byte 0


Naranja_IslaTangelo_G02_M01_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId1::
# 8 "data/maps/Naranja_IslaTangelo_G02_M01/scripts.pory"
	msgbox Naranja_IslaTangelo_G02_M01_Text_08174838, MSGBOX_NPC
	end


Naranja_IslaTangelo_G02_M01_EventScript_OBJ_EVENT_GFX_SCHOOL_KID_M_LocalId2::
# 13 "data/maps/Naranja_IslaTangelo_G02_M01/scripts.pory"
	msgbox Naranja_IslaTangelo_G02_M01_Text_0817487B, MSGBOX_NPC
	end


Naranja_IslaTangelo_G02_M01_Text_08174838::
# 17 "data/maps/Naranja_IslaTangelo_G02_M01/scripts.pory"
	.string "When POKéMON battle, they eventually\nlevel up and become stronger.$"

Naranja_IslaTangelo_G02_M01_Text_0817487B::
# 21 "data/maps/Naranja_IslaTangelo_G02_M01/scripts.pory"
	.string "If the POKéMON with you become\nstronger, you’ll be able to go farther\laway from here.$"
