Naranja_IslaValencia_G13_M16_MapScripts::
	.byte 0


Naranja_IslaValencia_G13_M16_EventScript_OBJ_EVENT_GFX_MAN_5_LocalId1::
# 8 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	loadword 0, Naranja_IslaValencia_G13_M16_Text_0818BEE8
# 9 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	callstd 2
	end


Naranja_IslaValencia_G13_M16_EventScript_OBJ_EVENT_GFX_MAN_1_LocalId2::
# 14 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	loadword 0, Naranja_IslaValencia_G13_M16_Text_0818BF4E
# 15 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	callstd 2
	end


Naranja_IslaValencia_G13_M16_Text_0818BEE8::
# 19 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	.string "’’Si mi voz muriera en tierra\nllevadla al nivel del mar\ly dejadla en la ribera.’’\pLo decía Alberti…$"

Naranja_IslaValencia_G13_M16_Text_0818BF4E::
# 23 "data/maps/Naranja_IslaValencia_G13_M16/scripts.pory"
	.string "Antes vivía en la isla MANDARIN,\nera una ciudad enorme y ruidosa\lcomparado con la tranquilidad de aquí$"
