Naranja_Route104_PrototypePrettyPetalFlowerShop_MapScripts::
	.byte 0


Naranja_Route104_PrototypePrettyPetalFlowerShop_EventScript_Girl1::
# 8 "data/maps/Naranja_Route104_PrototypePrettyPetalFlowerShop/scripts.pory"
	msgbox Naranja_Route104_PrototypePrettyPetalFlowerShop_Text_0819B436, MSGBOX_NPC
	end


Naranja_Route104_PrototypePrettyPetalFlowerShop_Text_0819B436::
# 12 "data/maps/Naranja_Route104_PrototypePrettyPetalFlowerShop/scripts.pory"
	.string "I have to stay home today.\pMy big sisters had to go out.\nThey said it was for preparations.\pIn the autumn, we’re going to start\na flower shop. Please wait for it!$"
