Naranja_IslaTangelo_G06_M06_MapScripts::
	.byte 0


Naranja_IslaTangelo_G06_M06_EventScript_OBJ_EVENT_GFX_LASS_LocalId1::
# 8 "data/maps/Naranja_IslaTangelo_G06_M06/scripts.pory"
	loadword 0, Naranja_IslaTangelo_G06_M06_Text_081BC0C3
# 9 "data/maps/Naranja_IslaTangelo_G06_M06/scripts.pory"
	callstd 4
# 10 "data/maps/Naranja_IslaTangelo_G06_M06/scripts.pory"
	release
	end


Naranja_IslaTangelo_G06_M06_Text_081BC0C3::
# 14 "data/maps/Naranja_IslaTangelo_G06_M06/scripts.pory"
	.string "¡Hey tìo! ¿Acaso es que ve tu culo\nque yo te moleste a tì?\p¡Déjame ver la tele, hermano!$"
