Naranja_IslaKumquat_G13_M05_MapScripts::
	.byte 0


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BOY_1_LocalId1::
# 8 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081890D4
# 9 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BOY_3_LocalId2::
# 14 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_0818915F
# 15 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_GIRL_3_LocalId3::
# 20 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189221
# 21 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_SAILOR_LocalId32::
# 26 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189299
# 27 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId4::
# 32 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189301
# 33 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 34 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 35 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_4, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 36 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 37 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_CONTEST_JUDGE_LocalId5::
# 42 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189366
# 43 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 44 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 45 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_CONTEST_JUDGE, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 46 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 47 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BLACK_BELT_LocalId6::
# 52 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081893CE
# 53 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 54 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 55 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_BLACK_BELT, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 56 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 57 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_OLD_MAN_1_LocalId7::
# 62 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189463
# 63 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 64 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 65 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_OLD_MAN_1, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 66 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 67 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_MANIAC_LocalId8::
# 72 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189512
# 73 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 74 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 75 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_MANIAC, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 76 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 77 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_6_LocalId9::
# 82 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_0818956B
# 83 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 84 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 85 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_6, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 86 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 87 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_OLD_WOMAN_1_LocalId10::
# 92 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081895F3
# 93 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 3
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BOY_1_LocalId12::
# 98 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189617
# 99 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 100 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 101 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_BOY_1_12, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 102 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 103 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_CAMPER_LocalId22::
# 108 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081896BE
# 109 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 110 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 111 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_CAMPER, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 112 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 113 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_7_LocalId11::
# 118 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081896FE
# 119 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 120 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 121 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_7, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 122 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 123 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId13::
# 128 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189771
# 129 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 130 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 131 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_4_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 132 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 133 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_CONTEST_JUDGE_LocalId14::
# 138 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_081897AA
# 139 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 140 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 141 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_CONTEST_JUDGE_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 142 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 143 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_5_LocalId15::
# 148 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_0818980B
# 149 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 150 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 151 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_5, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 152 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 153 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_LITTLE_GIRL_1_LocalId16::
# 158 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189874
# 159 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 160 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 161 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_LITTLE_GIRL_1, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 162 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 163 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_PSYCHIC_M_LocalId17::
# 168 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_0818990A
# 169 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 170 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 171 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_PSYCHIC_M, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 172 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 173 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId18::
# 178 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189981
# 179 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 180 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 181 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 182 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 183 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_3_LocalId19::
# 188 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189A1D
# 189 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 190 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 191 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_3, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 192 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 193 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_MAN_1_LocalId21::
# 198 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189A82
# 199 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 200 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 201 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_MAN_1_21, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 202 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 203 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_1_LocalId20::
# 208 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189AE1
# 209 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 210 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 211 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_1_20, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 212 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 213 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId23::
# 218 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189B4E
# 219 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 220 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 221 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_4_3, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 222 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 223 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_CONTEST_JUDGE_LocalId24::
# 228 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189BBF
# 229 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 230 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 231 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_CONTEST_JUDGE_3, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 232 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 233 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BOY_2_LocalId25::
# 238 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189C29
# 239 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 240 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 241 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_BOY_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 242 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 243 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_GIRL_2_LocalId26::
# 248 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189C67
# 249 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 250 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 251 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_GIRL_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 252 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 253 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_BOY_3_LocalId27::
# 258 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189CB3
# 259 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 260 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 261 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_BOY_3_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 262 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 263 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_OLD_WOMAN_1_LocalId28::
# 268 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189D11
# 269 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 270 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 271 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_OLD_WOMAN_1_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 272 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 273 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_WOMAN_3_LocalId29::
# 278 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 279 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_3_2, Naranja_IslaKumquat_G00_M05_Movement_081A0839
# 280 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 281 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	delay 0x19
# 282 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_WOMAN_3_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 283 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 284 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189DA2
# 285 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 3
# 286 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_LITTLE_GIRL_2_LocalId31::
# 291 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189E5F
# 292 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 293 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 294 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_LITTLE_GIRL_2, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 295 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 296 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_OBJ_EVENT_GFX_MAN_1_LocalId30::
# 301 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189DF3
# 302 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 2
# 303 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	lockall
# 304 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	applymovement LOCALID_ISLA_KUMQUAT_G13_M05_MAN_1_30, Naranja_CuevaDeCristal_G24_M04_Movement_081A083D
# 305 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	waitmovement LOCALID_NONE
# 306 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	releaseall
	end


Naranja_IslaKumquat_G13_M05_EventScript_Sign_1::
# 311 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189EF3
# 312 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 3
	end


Naranja_IslaKumquat_G13_M05_EventScript_Sign_2::
# 317 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189F29
# 318 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 3
	end


Naranja_IslaKumquat_G13_M05_EventScript_Sign_3::
# 323 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	loadword 0, Naranja_IslaKumquat_G13_M05_Text_08189F5C
# 324 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	callstd 3
	end


Naranja_IslaKumquat_G13_M05_Text_081890D4::
# 328 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "This POKéMON won the BEAUTY CONTEST\nhere before.\pWell, guess what? Today, I made it\nwin a SMARTNESS CONTEST!\pMy abilities scare even me...$"

Naranja_IslaKumquat_G13_M05_Text_0818915F::
# 332 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "I’ve entered a bunch of CONTESTS,\nso I’m seeing how things work.\pIf you’re in a COOLNESS CONTEST,\ncool moves go over as appeals.\pBut smart moves and cute moves\ndon’t go over well, for instance.$"

Naranja_IslaKumquat_G13_M05_Text_08189221::
# 336 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "That young man who won earlier had\na whole bunch of different オカキクケS.\pCan you win if you had that many\nof those things?$"

Naranja_IslaKumquat_G13_M05_Text_08189299::
# 340 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Whoa, isn’t this place humongous!\pThe tension in the air... It’s not\nlike a CONTEST hall in the sticks.$"

Naranja_IslaKumquat_G13_M05_Text_08189301::
# 344 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "MC: Okay, SMART POKéMON and their\nTRAINERS, are you ready?!\pGive it your best showing!\nLet’s appeal!$"

Naranja_IslaKumquat_G13_M05_Text_08189366::
# 348 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "JUDGE: Are you enjoying this CONTEST?\pCome back with three friends, and\nall of you may enter a CONTEST!$"

Naranja_IslaKumquat_G13_M05_Text_081893CE::
# 352 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Ayayayay...\nI entered the wrong CONTEST.\pI entered this tough POKéMON in the\nSMARTNESS CONTEST...\pCome on, wow them with a smart-looking\nROCK SMASH.$"

Naranja_IslaKumquat_G13_M05_Text_08189463::
# 356 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "I’ve spent many a year, and all my\nwisdom besides, raising this POKéMON\lto be smart.\pIt won’t be easily bested by some\nyoung pup’s POKéMON.\pMy dear wife, are you seeing this?$"

Naranja_IslaKumquat_G13_M05_Text_08189512::
# 360 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "There it is!\pIf my POKéMON pulls a smart move next,\nthe audience’s excitement will peak!$"

Naranja_IslaKumquat_G13_M05_Text_0818956B::
# 364 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Oh, dear, no!\pMy darling ZUBAT’s LEECH LIFE is so\ncute I kept using it over and over!\pBut these mean people don’t appreciate\nit at all!$"

Naranja_IslaKumquat_G13_M05_Text_081895F3::
# 368 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Kiyaaah! You’re beautiful, Grandpa!$"

Naranja_IslaKumquat_G13_M05_Text_08189617::
# 372 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Even when TRAINERS enter the same\nkind of POKéMON, they all seem to use\ldifferent moves for appeals.\pIt’s just like the way people have\ndifferent styles for battling.$"

Naranja_IslaKumquat_G13_M05_Text_081896BE::
# 376 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "I think the POKéMON look smarter\nthan their TRAINERS. By a lot.$"

Naranja_IslaKumquat_G13_M05_Text_081896FE::
# 380 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "When all’s said and done, I still love\nSMARTNESS CONTESTS.\pThat intellectual green color...\nIt’s so... So... Cool.$"

Naranja_IslaKumquat_G13_M05_Text_08189771::
# 384 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "MC: Are you entering the BEAUTY\nCONTEST, too? Good luck!$"

Naranja_IslaKumquat_G13_M05_Text_081897AA::
# 388 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "JUDGE: Ah, every POKéMON here is a\nmodel of pristine beauty!\pWhy, I almost forgot to score them!$"

Naranja_IslaKumquat_G13_M05_Text_0818980B::
# 392 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "A POKéMON this beautiful...\nThere isn’t another one like it.\pEveryone’s eyes will be glued to\nmy beauty.$"

Naranja_IslaKumquat_G13_M05_Text_08189874::
# 396 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Waaaah!\pI brushed and groomed my POKéMON\ncarefully for this CONTEST...\pBut I overdid it...\nMy POKéMON’s coat turned all scraggly...\pWhat should I do?$"

Naranja_IslaKumquat_G13_M05_Text_0818990A::
# 400 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "This AURORA BEAM is so dazzling,\nthe JUDGE won’t be able to see it.\pUh, wait a second...\nThat’ll be meaningless, then!$"

Naranja_IslaKumquat_G13_M05_Text_08189981::
# 404 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "This pretty POKéMON looks just like\nme when I was younger.\pRight when I said that, my husband\nspewed the coffee he was drinking.\pDid I say something funny?$"

Naranja_IslaKumquat_G13_M05_Text_08189A1D::
# 408 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "You know, as a woman, if I win at a\nBEAUTY CONTEST, sure it makes me\lhappy. More than usual, anyway.$"

Naranja_IslaKumquat_G13_M05_Text_08189A82::
# 412 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Wahahahah!\pWill you take a gander at all those\npretty POKéMON!\lI just love this sort of glitz!$"

Naranja_IslaKumquat_G13_M05_Text_08189AE1::
# 416 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "You can’t always win on just beauty\nalone.\pYou have to groom your POKéMON so\nit’s nice and glossy like mine.$"

Naranja_IslaKumquat_G13_M05_Text_08189B4E::
# 420 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "MC: Uh-oh! Hello!\nWe’re in the middle of a CONTEST!\pPlease enter at our registration\ncounter and come out, okay?$"

Naranja_IslaKumquat_G13_M05_Text_08189BBF::
# 424 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "JUDGE: Oh, such charming and cute\nappeals!\pOh, my goodness! What a perfectly\nadorable WATER SPORT appeal!$"

Naranja_IslaKumquat_G13_M05_Text_08189C29::
# 428 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Oh, no... My sweet AZURILL was\ndistracted by another POKéMON.$"

Naranja_IslaKumquat_G13_M05_Text_08189C67::
# 432 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "My POKéMON has never won in a battle,\nbut put it in a CONTEST and look out!$"

Naranja_IslaKumquat_G13_M05_Text_08189CB3::
# 436 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "My POKéMON’s PETAL DANCE is a marvel\nof elegance.\pI won’t let anyone disturb its\nperformance.$"

Naranja_IslaKumquat_G13_M05_Text_08189D11::
# 440 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Everyone’s POKéMON are very cute.\pHowever, if my POKéMON were to make\na cute appeal...\pI’m sure that it would be so much \ncuter than the others.$"

Naranja_IslaKumquat_G13_M05_Text_08189DA2::
# 444 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "My child is in this CONTEST.\pCome on, dear. Go for it!\nYour POKéMON is the best!$"

Naranja_IslaKumquat_G13_M05_Text_08189DF3::
# 448 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "I think that girl over there is the\ncutest of the lot.\pWhat’s that? They’re judging\nPOKéMON by their looks?$"

Naranja_IslaKumquat_G13_M05_Text_08189E5F::
# 452 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "Ohh, seeing all these cute POKéMON,\nthey make we want to get my own!\pI’m going to go catch some!$"

Naranja_IslaKumquat_G13_M05_Text_08189EF3::
# 456 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "BEAUTY CONTEST STAGE\nBE ALLURED BY BEAUTIFUL POKéMON!$"

Naranja_IslaKumquat_G13_M05_Text_08189F29::
# 460 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "CUTENESS CONTEST STAGE\nBE CHARMED BY CUTE POKéMON!$"

Naranja_IslaKumquat_G13_M05_Text_08189F5C::
# 464 "data/maps/Naranja_IslaKumquat_G13_M05/scripts.pory"
	.string "SMARTNESS CONTEST STAGE\nBE IMPRESSED BY SMART POKéMON!$"
