Naranja_TrovitaIsland_House2_MapScripts::
	.byte 0


Naranja_TrovitaIsland_House2_EventScript_Woman2::
# 8 "data/maps/Naranja_TrovitaIsland_House2/scripts.pory"
	msgbox Naranja_TrovitaIsland_House2_Text_0818532D, MSGBOX_NPC
	end


Naranja_TrovitaIsland_House2_EventScript_LittleGirl2::
# 13 "data/maps/Naranja_TrovitaIsland_House2/scripts.pory"
	msgbox Naranja_TrovitaIsland_House2_Text_08185388, MSGBOX_NPC
	end


Naranja_TrovitaIsland_House2_Text_0818532D::
# 17 "data/maps/Naranja_TrovitaIsland_House2/scripts.pory"
	.string "The TRAINER’S SCHOOL is excellent.\pIf you study there, you could even\nbecome a GYM LEADER.$"

Naranja_TrovitaIsland_House2_Text_08185388::
# 21 "data/maps/Naranja_TrovitaIsland_House2/scripts.pory"
	.string "ROXANNE, the GYM LEADER, really knows\na lot about POKéMON.\pShe’s really strong, too!$"
