Naranja_IslaTrovita_G11_M15_MapScripts::
	.byte 0


Naranja_IslaTrovita_G11_M15_EventScript_OBJ_EVENT_GFX_MAN_7_LocalId1::
# 8 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	loadword 0, Naranja_IslaTrovita_G11_M15_Text_0818551D
# 9 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	callstd 2
	end


Naranja_IslaTrovita_G11_M15_EventScript_OBJ_EVENT_GFX_WOMAN_1_LocalId2::
# 14 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	loadword 0, Naranja_IslaTrovita_G11_M15_Text_0818554D
# 15 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	callstd 2
	end


Naranja_IslaTrovita_G11_M15_Text_0818551D::
# 19 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	.string "DEVON’s PRESIDENT likes to collect\nrare stones.$"

Naranja_IslaTrovita_G11_M15_Text_0818554D::
# 23 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	.string "I think the PRESIDENT’s son also\ncollects rare stones.$"
