Naranja_IslaTrovita_G11_M15_MapScripts::
	.byte 0


Naranja_IslaTrovita_G11_M15_EventScript_OBJ_EVENT_GFX_MAN_7_LocalId1::
# 8 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	msgbox Naranja_IslaTrovita_G11_M15_Text_0818551D, MSGBOX_NPC
	end


Naranja_IslaTrovita_G11_M15_EventScript_OBJ_EVENT_GFX_WOMAN_1_LocalId2::
# 13 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	msgbox Naranja_IslaTrovita_G11_M15_Text_0818554D, MSGBOX_NPC
	end


Naranja_IslaTrovita_G11_M15_Text_0818551D::
# 17 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	.string "DEVON’s PRESIDENT likes to collect\nrare stones.$"

Naranja_IslaTrovita_G11_M15_Text_0818554D::
# 21 "data/maps/Naranja_IslaTrovita_G11_M15/scripts.pory"
	.string "I think the PRESIDENT’s son also\ncollects rare stones.$"
