Naranja_SafariZone_RestHouse_MapScripts::
	.byte 0


Naranja_SafariZone_RestHouse_EventScript_Youngster::
# 8 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	msgbox Naranja_SafariZone_RestHouse_Text_081C3EC9, MSGBOX_NPC
	end


Naranja_SafariZone_RestHouse_EventScript_PsychicM::
# 13 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	msgbox Naranja_SafariZone_RestHouse_Text_081C3F71, MSGBOX_NPC
	end


Naranja_SafariZone_RestHouse_EventScript_FatMan::
# 18 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	msgbox Naranja_SafariZone_RestHouse_Text_081C3FF4, MSGBOX_NPC
	end


Naranja_SafariZone_RestHouse_Text_081C3EC9::
# 22 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	.string "I don’t have any オカキクケS, but I caught\na good number of POKéMON.\pYou can improve your chances of making\na catch by getting closer to them\lbefore throwing a SAFARI BALL.$"

Naranja_SafariZone_RestHouse_Text_081C3F71::
# 26 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	.string "If you use オカキクケS, wild POKéMON won’t\nbe so quick to run away.\pIt’s not much use to give オカキクケS to\nPOKéMON that don’t flee easily.$"

Naranja_SafariZone_RestHouse_Text_081C3FF4::
# 30 "data/maps/Naranja_SafariZone_RestHouse/scripts.pory"
	.string "If you put a オカキクケ on the FEEDER,\nPOKéMON are attracted to it.\pI think POKéMON with the same sort of\nnature are drawn by a certain オカキクケ.$"
