Naranja_NewIsland_Gym_B1F_MapScripts::
	.byte 0


Naranja_NewIsland_Gym_B1F_EventScript_Lass::
# 8 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_613, Naranja_NewIsland_Gym_B1F_Text_0818EA87, Naranja_NewIsland_Gym_B1F_Text_0818EACF
# 9 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EAED, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Lass_2::
# 14 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_614, Naranja_NewIsland_Gym_B1F_Text_0818EB22, Naranja_NewIsland_Gym_B1F_Text_0818EB81
# 15 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EBB1, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Woman3::
# 20 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_118, Naranja_NewIsland_Gym_B1F_Text_0818EBFA, Naranja_NewIsland_Gym_B1F_Text_0818EC5E
# 21 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EC92, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Beauty::
# 26 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_128, Naranja_NewIsland_Gym_B1F_Text_0818ECEB, Naranja_NewIsland_Gym_B1F_Text_0818ED18
# 27 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818ED2B, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Beauty_2::
# 32 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_129, Naranja_NewIsland_Gym_B1F_Text_0818ED91, Naranja_NewIsland_Gym_B1F_Text_0818EDE8
# 33 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EE03, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Beauty_4::
# 38 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_130, Naranja_NewIsland_Gym_B1F_Text_0818EE96, Naranja_NewIsland_Gym_B1F_Text_0818EEDC
# 39 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EEF7, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Beauty_3::
# 44 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_131, Naranja_NewIsland_Gym_B1F_Text_0818EF39, Naranja_NewIsland_Gym_B1F_Text_0818EFB8
# 45 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818EFCA, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_EventScript_Woman2::
# 50 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_NARANJA_NEW_ISLAND_301, Naranja_NewIsland_Gym_B1F_Text_0818F037, Naranja_NewIsland_Gym_B1F_Text_0818F07F
# 51 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	msgbox Naranja_NewIsland_Gym_B1F_Text_0818F085, MSGBOX_AUTOCLOSE
	end


Naranja_NewIsland_Gym_B1F_Text_0818EA87::
# 55 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I’ll show you the sublime techniques\nI learned from our LEADER WALLACE!$"

Naranja_NewIsland_Gym_B1F_Text_0818EACF::
# 59 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Please forgive me, WALLACE...$"

Naranja_NewIsland_Gym_B1F_Text_0818EAED::
# 63 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Watch what happens if you crack all\nthe floor tiles.$"

Naranja_NewIsland_Gym_B1F_Text_0818EB22::
# 67 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "You came all the way here, but you won’t\nget to see WALLACE.\pNot if you lose to me, you won’t!$"

Naranja_NewIsland_Gym_B1F_Text_0818EB81::
# 71 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "You’re strong!\nI was fooled by your cute looks!$"

Naranja_NewIsland_Gym_B1F_Text_0818EBB1::
# 75 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "You might be good enough to avoid\nbeing wiped out in one hit by WALLACE.$"

Naranja_NewIsland_Gym_B1F_Text_0818EBFA::
# 79 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "The sight of WALLACE conducting a\nbattle...\pThe very beauty of it compelled me to\nbecome a TRAINER.$"

Naranja_NewIsland_Gym_B1F_Text_0818EC5E::
# 83 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "You battled with more beauty than\nI could muster...$"

Naranja_NewIsland_Gym_B1F_Text_0818EC92::
# 87 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "The grace you bring to battle is\nfabulous.\pOh... I’m so fortunate to have found\nPOKéMON.$"

Naranja_NewIsland_Gym_B1F_Text_0818ECEB::
# 91 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I should teach you how harsh battles\ncan be.$"

Naranja_NewIsland_Gym_B1F_Text_0818ED18::
# 95 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Oh.\nYou’re strong.$"

Naranja_NewIsland_Gym_B1F_Text_0818ED2B::
# 99 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I’ll tell you something good.\pIf you want to reach WALLACE, you\nneed to walk on each floor tile once.$"

Naranja_NewIsland_Gym_B1F_Text_0818ED91::
# 103 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "The POKéMON GYM of the highest level\nin the HOENN region...\pThat’s the SOOTOPOLIS GYM.$"

Naranja_NewIsland_Gym_B1F_Text_0818EDE8::
# 107 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "What a high level you are!$"

Naranja_NewIsland_Gym_B1F_Text_0818EE03::
# 111 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Rather than being satisfied by being\nin a strong GYM, I imagine training in\lother places will make you stronger.\lBut above all, it looks more fun.$"

Naranja_NewIsland_Gym_B1F_Text_0818EE96::
# 115 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I train my POKéMON together with\nWALLACE.\pDon’t think I’m a pushover.$"

Naranja_NewIsland_Gym_B1F_Text_0818EEDC::
# 119 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I was bowled right over...$"

Naranja_NewIsland_Gym_B1F_Text_0818EEF7::
# 123 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I think you have potential.\nWhy don’t you stay and train with us?$"

Naranja_NewIsland_Gym_B1F_Text_0818EF39::
# 127 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "A graceful glide across the ice while\ncrossing no lines...\pA TRAINER putting on that performance\nwould be elegantly beautiful!$"

Naranja_NewIsland_Gym_B1F_Text_0818EFB8::
# 131 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Well, excuse me?!$"

Naranja_NewIsland_Gym_B1F_Text_0818EFCA::
# 135 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "This is really obvious, but how strong\nyou are as a TRAINER has nothing to do\lwith how young or old you are.$"

Naranja_NewIsland_Gym_B1F_Text_0818F037::
# 139 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "When I’m with my POKéMON, the time\nflies by before you can say, “Oops!”$"

Naranja_NewIsland_Gym_B1F_Text_0818F07F::
# 143 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "Oops!$"

Naranja_NewIsland_Gym_B1F_Text_0818F085::
# 147 "data/maps/Naranja_NewIsland_Gym_B1F/scripts.pory"
	.string "I wish I can forget about lost causes\nbefore I can manage an “Oops!”$"
