Naranja_TrovitaIsland_Flat2_3F_MapScripts::
	.byte 0


Naranja_TrovitaIsland_Flat2_3F_EventScript_Man7::
# 8 "data/maps/Naranja_TrovitaIsland_Flat2_3F/scripts.pory"
	msgbox Naranja_TrovitaIsland_Flat2_3F_Text_0818551D, MSGBOX_NPC
	end


Naranja_TrovitaIsland_Flat2_3F_EventScript_Woman1::
# 13 "data/maps/Naranja_TrovitaIsland_Flat2_3F/scripts.pory"
	msgbox Naranja_TrovitaIsland_Flat2_3F_Text_0818554D, MSGBOX_NPC
	end


Naranja_TrovitaIsland_Flat2_3F_Text_0818551D::
# 17 "data/maps/Naranja_TrovitaIsland_Flat2_3F/scripts.pory"
	.string "DEVON’s PRESIDENT likes to collect\nrare stones.$"

Naranja_TrovitaIsland_Flat2_3F_Text_0818554D::
# 21 "data/maps/Naranja_TrovitaIsland_Flat2_3F/scripts.pory"
	.string "I think the PRESIDENT’s son also\ncollects rare stones.$"
