Naranja_Route110_SeasideCyclingRoadSouthEntrance_MapScripts::
	.byte 0


Naranja_Route110_SeasideCyclingRoadSouthEntrance_EventScript_MartEmployee::
# 8 "data/maps/Naranja_Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	lock
# 9 "data/maps/Naranja_Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	faceplayer
# 10 "data/maps/Naranja_Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	msgbox Naranja_Route110_SeasideCyclingRoadSouthEntrance_Text_0819E326, MSGBOX_DEFAULT
# 11 "data/maps/Naranja_Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	release
	end


Naranja_Route110_SeasideCyclingRoadSouthEntrance_Text_0819E326::
# 15 "data/maps/Naranja_Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	.string "On CYCLING ROAD, you can go all out\nand cycle as fast as you’d like.\pIt feels great to go that fast, but try\nnot to crash into anyone!$"
