Naranja_NewIsland_House5_MapScripts::
	.byte 0


Naranja_NewIsland_House5_EventScript_Maniac::
# 8 "data/maps/Naranja_NewIsland_House5/scripts.pory"
	msgbox Naranja_NewIsland_House5_Text_0818FDEC, MSGBOX_NPC
	end


Naranja_NewIsland_House5_EventScript_Girl3::
# 13 "data/maps/Naranja_NewIsland_House5/scripts.pory"
	msgbox Naranja_NewIsland_House5_Text_0818FE7B, MSGBOX_NPC
	end


Naranja_NewIsland_House5_Text_0818FDEC::
# 17 "data/maps/Naranja_NewIsland_House5/scripts.pory"
	.string "There appears to be some connection\nbetween SOOTOPOLIS and MT. PYRE.\pMy friends and I did some research on\nit at the lab where I used to work.$"

Naranja_NewIsland_House5_Text_0818FE7B::
# 21 "data/maps/Naranja_NewIsland_House5/scripts.pory"
	.string "My big brother used to study the sea.$"
