Naranja_IslaMandarina_G06_M01_MapScripts::
	.byte 0


Naranja_IslaMandarina_G06_M01_EventScript_OBJ_EVENT_GFX_BOY_3_LocalId2::
# 8 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G06_M01_Text_08177FB4
# 9 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	callstd 2
	end


Naranja_IslaMandarina_G06_M01_EventScript_OBJ_EVENT_GFX_LITTLE_GIRL_2_LocalId3::
# 14 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G06_M01_Text_08178091
# 15 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	callstd 2
	end


Naranja_IslaMandarina_G06_M01_EventScript_OBJ_EVENT_GFX_BOY_4_LocalId1::
# 20 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G06_M01_Text_08178120
# 21 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	callstd 2
	end


Naranja_IslaMandarina_G06_M01_EventScript_Sign_1::
# 26 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G06_M01_Text_081781A5
# 27 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	callstd 3
	end


Naranja_IslaMandarina_G06_M01_Text_08177FB4::
# 31 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	.string "Which CONTEST are you entering?\nWant a piece of advice?\pIn any CONTEST, for example, a CUTE\nCONTEST, I don’t think they judge you\lonly on cuteness in the first round.\pYou need to work out ways for raising\nPOKéMON better.$"

Naranja_IslaMandarina_G06_M01_Text_08178091::
# 35 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	.string "I raised my POKéMON to be cute.\pI found out you can put POKéMON in\na CONTEST for cuteness!\pI’m so glad I raised my POKéMON with\nloving care...$"

Naranja_IslaMandarina_G06_M01_Text_08178120::
# 39 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	.string "My POKéMON rules!\pIt’s cool, tough yet beautiful, cute,\nand smart. It’s complete!\pI may as well go for wins in every\nsingle CONTEST.$"

Naranja_IslaMandarina_G06_M01_Text_081781A5::
# 43 "data/maps/Naranja_IslaMandarina_G06_M01/scripts.pory"
	.string "POKéMON CONTESTS\nNORMAL RANK STAGE!$"
