Naranja_Route110_G29_M11_MapScripts::
	.byte 0


Naranja_Route110_G29_M11_EventScript_OBJ_EVENT_GFX_MART_EMPLOYEE_LocalId1::
# 8 "data/maps/Naranja_Route110_G29_M11/scripts.pory"
	lock
# 9 "data/maps/Naranja_Route110_G29_M11/scripts.pory"
	faceplayer
# 10 "data/maps/Naranja_Route110_G29_M11/scripts.pory"
	msgbox Naranja_Route110_G29_M11_Text_0819E326, MSGBOX_DEFAULT
# 11 "data/maps/Naranja_Route110_G29_M11/scripts.pory"
	release
	end


Naranja_Route110_G29_M11_Text_0819E326::
# 15 "data/maps/Naranja_Route110_G29_M11/scripts.pory"
	.string "On CYCLING ROAD, you can go all out\nand cycle as fast as you’d like.\pIt feels great to go that fast, but try\nnot to crash into anyone!$"
