Naranja_TrovitaIsland_Flat1_2F_MapScripts::
	.byte 0


Naranja_TrovitaIsland_Flat1_2F_EventScript_Woman2::
# 8 "data/maps/Naranja_TrovitaIsland_Flat1_2F/scripts.pory"
	msgbox Naranja_TrovitaIsland_Flat1_2F_Text_08184E0D, MSGBOX_NPC
	end


Naranja_TrovitaIsland_Flat1_2F_Text_08184E0D::
# 12 "data/maps/Naranja_TrovitaIsland_Flat1_2F/scripts.pory"
	.string "Oh, it’s so hard every day...\pWhat’s hard?\nYou need to ask?\pIt’s trying to figure out what to\nmake for meals every day.\pIt really isn’t easy coming up with\nmeals every day.$"
