Naranja_IslaNueva_G15_M01_MapScripts::
	.byte 0


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_LASS_LocalId1::
# 8 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_613, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818EA87, Naranja_IslaNueva_G15_M01_Text_0818EACF
# 9 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EAED
# 10 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_LASS_LocalId7::
# 15 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_614, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818EB22, Naranja_IslaNueva_G15_M01_Text_0818EB81
# 16 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EBB1
# 17 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_WOMAN_3_LocalId3::
# 22 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_118, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818EBFA, Naranja_IslaNueva_G15_M01_Text_0818EC5E
# 23 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EC92
# 24 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_BEAUTY_LocalId2::
# 29 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_128, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818ECEB, Naranja_IslaNueva_G15_M01_Text_0818ED18
# 30 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818ED2B
# 31 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_BEAUTY_LocalId4::
# 36 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_129, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818ED91, Naranja_IslaNueva_G15_M01_Text_0818EDE8
# 37 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EE03
# 38 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_BEAUTY_LocalId8::
# 43 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_130, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818EE96, Naranja_IslaNueva_G15_M01_Text_0818EEDC
# 44 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EEF7
# 45 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_BEAUTY_LocalId5::
# 50 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_131, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818EF39, Naranja_IslaNueva_G15_M01_Text_0818EFB8
# 51 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818EFCA
# 52 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId6::
# 57 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_NARANJA_ISLA_NUEVA_301, LOCALID_NONE, Naranja_IslaNueva_G15_M01_Text_0818F037, Naranja_IslaNueva_G15_M01_Text_0818F07F
# 58 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	loadword 0, Naranja_IslaNueva_G15_M01_Text_0818F085
# 59 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	callstd 6
	end


Naranja_IslaNueva_G15_M01_Text_0818EA87::
# 63 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I’ll show you the sublime techniques\nI learned from our LEADER WALLACE!$"

Naranja_IslaNueva_G15_M01_Text_0818EACF::
# 67 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Please forgive me, WALLACE...$"

Naranja_IslaNueva_G15_M01_Text_0818EAED::
# 71 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Watch what happens if you crack all\nthe floor tiles.$"

Naranja_IslaNueva_G15_M01_Text_0818EB22::
# 75 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "You came all the way here, but you won’t\nget to see WALLACE.\pNot if you lose to me, you won’t!$"

Naranja_IslaNueva_G15_M01_Text_0818EB81::
# 79 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "You’re strong!\nI was fooled by your cute looks!$"

Naranja_IslaNueva_G15_M01_Text_0818EBB1::
# 83 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "You might be good enough to avoid\nbeing wiped out in one hit by WALLACE.$"

Naranja_IslaNueva_G15_M01_Text_0818EBFA::
# 87 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "The sight of WALLACE conducting a\nbattle...\pThe very beauty of it compelled me to\nbecome a TRAINER.$"

Naranja_IslaNueva_G15_M01_Text_0818EC5E::
# 91 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "You battled with more beauty than\nI could muster...$"

Naranja_IslaNueva_G15_M01_Text_0818EC92::
# 95 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "The grace you bring to battle is\nfabulous.\pOh... I’m so fortunate to have found\nPOKéMON.$"

Naranja_IslaNueva_G15_M01_Text_0818ECEB::
# 99 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I should teach you how harsh battles\ncan be.$"

Naranja_IslaNueva_G15_M01_Text_0818ED18::
# 103 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Oh.\nYou’re strong.$"

Naranja_IslaNueva_G15_M01_Text_0818ED2B::
# 107 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I’ll tell you something good.\pIf you want to reach WALLACE, you\nneed to walk on each floor tile once.$"

Naranja_IslaNueva_G15_M01_Text_0818ED91::
# 111 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "The POKéMON GYM of the highest level\nin the HOENN region...\pThat’s the SOOTOPOLIS GYM.$"

Naranja_IslaNueva_G15_M01_Text_0818EDE8::
# 115 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "What a high level you are!$"

Naranja_IslaNueva_G15_M01_Text_0818EE03::
# 119 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Rather than being satisfied by being\nin a strong GYM, I imagine training in\lother places will make you stronger.\lBut above all, it looks more fun.$"

Naranja_IslaNueva_G15_M01_Text_0818EE96::
# 123 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I train my POKéMON together with\nWALLACE.\pDon’t think I’m a pushover.$"

Naranja_IslaNueva_G15_M01_Text_0818EEDC::
# 127 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I was bowled right over...$"

Naranja_IslaNueva_G15_M01_Text_0818EEF7::
# 131 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I think you have potential.\nWhy don’t you stay and train with us?$"

Naranja_IslaNueva_G15_M01_Text_0818EF39::
# 135 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "A graceful glide across the ice while\ncrossing no lines...\pA TRAINER putting on that performance\nwould be elegantly beautiful!$"

Naranja_IslaNueva_G15_M01_Text_0818EFB8::
# 139 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Well, excuse me?!$"

Naranja_IslaNueva_G15_M01_Text_0818EFCA::
# 143 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "This is really obvious, but how strong\nyou are as a TRAINER has nothing to do\lwith how young or old you are.$"

Naranja_IslaNueva_G15_M01_Text_0818F037::
# 147 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "When I’m with my POKéMON, the time\nflies by before you can say, “Oops!”$"

Naranja_IslaNueva_G15_M01_Text_0818F07F::
# 151 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "Oops!$"

Naranja_IslaNueva_G15_M01_Text_0818F085::
# 155 "data/maps/Naranja_IslaNueva_G15_M01/scripts.pory"
	.string "I wish I can forget about lost causes\nbefore I can manage an “Oops!”$"
