Naranja_IslaTrovita_G11_M09_MapScripts::
	.byte 0


Naranja_IslaTrovita_G11_M09_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId1::
# 8 "data/maps/Naranja_IslaTrovita_G11_M09/scripts.pory"
	loadword 0, Naranja_IslaTrovita_G11_M09_Text_08184E0D
# 9 "data/maps/Naranja_IslaTrovita_G11_M09/scripts.pory"
	callstd 2
	end


Naranja_IslaTrovita_G11_M09_Text_08184E0D::
# 13 "data/maps/Naranja_IslaTrovita_G11_M09/scripts.pory"
	.string "Oh, it’s so hard every day...\pWhat’s hard?\nYou need to ask?\pIt’s trying to figure out what to\nmake for meals every day.\pIt really isn’t easy coming up with\nmeals every day.$"
