Naranja_IslaMandarina_G13_M21_MapScripts::
	.byte 0


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId3::
# 8 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	lock
# 9 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	faceplayer
# 10 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	message Naranja_CaminoFrio_G00_M29_Text_081A0BE4
# 11 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	waitmessage
# 12 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	pokemartdecoration2 Naranja_IslaMandarina_G13_M21_Mart_0815A078
# 13 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_CaminoFrio_G00_M29_Text_081A0C02
# 14 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 4
# 15 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	release
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId4::
# 20 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	lock
# 21 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	faceplayer
# 22 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	message Naranja_CaminoFrio_G00_M29_Text_081A0BE4
# 23 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	waitmessage
# 24 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	pokemartdecoration2 Naranja_IslaMandarina_G13_M21_Mart_0815A0AC
# 25 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_CaminoFrio_G00_M29_Text_081A0C02
# 26 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 4
# 27 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	release
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId5::
# 32 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	lock
# 33 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	faceplayer
# 34 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	message Naranja_CaminoFrio_G00_M29_Text_081A0BE4
# 35 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	waitmessage
# 36 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	pokemartdecoration2 Naranja_IslaMandarina_G13_M21_Mart_0815A0DC
# 37 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_CaminoFrio_G00_M29_Text_081A0C02
# 38 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 4
# 39 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	release
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_4_LocalId6::
# 44 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	lock
# 45 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	faceplayer
# 46 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	message Naranja_CaminoFrio_G00_M29_Text_081A0BE4
# 47 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	waitmessage
# 48 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	pokemartdecoration2 Naranja_IslaMandarina_G13_M21_Mart_0815A10C
# 49 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_CaminoFrio_G00_M29_Text_081A0C02
# 50 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 4
# 51 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	release
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_2_LocalId2::
# 56 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G13_M21_Text_0818C4F9
# 57 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 2
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_WOMAN_3_LocalId7::
# 62 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G13_M21_Text_0818C59F
# 63 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 2
	end


Naranja_IslaMandarina_G13_M21_EventScript_OBJ_EVENT_GFX_LITTLE_GIRL_2_LocalId1::
# 68 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	loadword 0, Naranja_IslaMandarina_G13_M21_Text_0818C556
# 69 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	callstd 2
	end


	.align 2
# 73 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
Naranja_IslaMandarina_G13_M21_Mart_0815A078:
# 74 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_X_DEFEND
# 75 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_X_SPEED
# 76 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_X_ACCURACY
# 77 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_SUPER_REPEL
# 78 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_05B
# 79 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_05C
# 80 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_SUN_STONE
# 81 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_MOON_STONE
# 82 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 83 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 84 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_WATER_STONE
# 85 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_LEAF_STONE
	.2byte ITEM_NONE

	.align 2
# 88 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
Naranja_IslaMandarina_G13_M21_Mart_0815A0AC:
# 89 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_065
# 90 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_066
# 91 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_BIG_MUSHROOM
# 92 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_069
# 93 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_PEARL
# 94 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_BIG_PEARL
# 95 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_STARDUST
# 96 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_STAR_PIECE
# 97 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_NUGGET
	.2byte ITEM_NONE

	.align 2
# 100 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
Naranja_IslaMandarina_G13_M21_Mart_0815A0DC:
# 101 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_CARBOS
# 102 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_CALCIUM
# 103 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_RARE_CANDY
# 104 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_PP_UP
# 105 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_ZINC
# 106 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_PP_MAX
# 107 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_048
# 108 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_GUARD_SPEC
# 109 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_DIRE_HIT
	.2byte ITEM_NONE

	.align 2
# 112 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
Naranja_IslaMandarina_G13_M21_Mart_0815A10C:
# 113 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_03B
# 114 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_03C
# 115 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_03D
# 116 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_03E
# 117 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_HP_UP
# 118 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_PROTEIN
# 119 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_IRON
# 120 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_RED_SHARD
# 121 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_BLUE_SHARD
# 122 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.2byte ITEM_YELLOW_SHARD
	.2byte ITEM_NONE

Naranja_IslaMandarina_G13_M21_Text_0818C4F9::
# 125 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.string "This place is full of cute DOLLS.\pI should buy some for me, instead of\njust for my children.$"

Naranja_IslaMandarina_G13_M21_Text_0818C556::
# 129 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.string "I’m not big enough to raise POKéMON,\nso I’m getting a cute DOLL instead.$"

Naranja_IslaMandarina_G13_M21_Text_0818C59F::
# 133 "data/maps/Naranja_IslaMandarina_G13_M21/scripts.pory"
	.string "They sell many cute MATS here.\pI wonder which one I should get?\nMaybe I’ll buy them all...$"
